### ISSUE TITLE
Bizeles 4x3 1024 x768

### ISSUE THREAD

**Issue by Roberto7999** [svera/vertical-bezels-4-3#17]
![tigerh](https://user-images.githubusercontent.com/69028407/159178448-5f2c8dbf-f1cf-4db4-ab09-f6194e364214.png)
![vastar](https://user-images.githubusercontent.com/69028407/159178456-d0439dba-c35d-433b-9134-7ef3979ff97d.png)
![zzyzzyxx](https://user-images.githubusercontent.com/69028407/159178457-0b4391ef-21b4-4b21-aa18-4c72a6ba846e.png)
![kageki](https://user-images.githubusercontent.com/69028407/159178460-42676345-794b-4a60-95fe-7ce4e5838731.png)
![outzone](https://user-images.githubusercontent.com/69028407/159178462-7cc52394-91e7-406d-a4cd-24ef5f9a0fb3.png)
![raiden](https://user-images.githubusercontent.com/69028407/159178464-ef1db643-f365-4c8e-b1be-b7294c752f86.png)
![scobra](https://user-images.githubusercontent.com/69028407/159178465-d742659b-18d7-4605-bb20-51423728db65.png)
![scontra](https://user-images.githubusercontent.com/69028407/159178467-d1ac38fb-bb97-4e90-80e6-e777f0b4ff04.png)
![springer](https://user-images.githubusercontent.com/69028407/159178469-2d569f4f-dfae-4350-b5f5-965bc58fd28b.png)
![spyhunt](https://user-images.githubusercontent.com/69028407/159178470-afb11147-0ede-456e-a96e-ec9fbe173cfc.png)
![twinbee](https://user-images.githubusercontent.com/69028407/159178471-110e5719-e96a-417c-bddc-89539021f106.png)
![jackal](https://user-images.githubusercontent.com/69028407/159178477-7659e592-b6f0-43d4-818b-ea538643e596.png)
![ddp2](https://user-images.githubusercontent.com/69028407/159178479-8647da28-b0a8-44a3-b2a7-144866fb912e.png)
![devstors](https://user-images.githubusercontent.com/69028407/159178480-2a56d90e-6f72-4352-ae4e-b79b34515436.png)
![donpachi](https://user-images.githubusercontent.com/69028407/159178482-7363195d-4d71-4753-85af-e13ec0f19bd5.png)
![fshark](https://user-images.githubusercontent.com/69028407/159178483-82c046d3-cf69-4b48-b6eb-a81c8db0eeec.png)
![invaders](https://user-images.githubusercontent.com/69028407/159178485-c6446bd7-1015-4362-a14a-19755a636c99.png)
![invadpt2](https://user-images.githubusercontent.com/69028407/159178486-0d66c3ba-70ee-4cb4-b9db-6648c6480990.png)

**Comment by svera** [comment]
Hi @Roberto7999 , thank you for these bezels! There are several issues though:

1. You opened an issue, but I need you to open a Pull Request instead. You can see there is a Pull Requests tab just beside the one for issues, go there and create a new one, adding all required files.
2. The bezels you added are only 1024x768, but we also require versions with resolution 1600x1200.
3. Also, we also need the support config files for each of these bezels.

You can see an example of a pull request with all required files [here](https://github.com/svera/vertical-bezels-4-3/pull/10)
